### PR TITLE
Create Anti Ban Code

### PR DESCRIPTION
**Pull request by Doomlands**

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
make it a .js file

**Comment by Doomlands** [comment]
Working on making new codes they should be done by tomorrow

**Comment by 3kh0** [comment]
Still, make it a js file

**Comment by Doomlands** [comment]
I will by the end of the day

**Comment by Jude-Gideon** [comment]
how about, make your own code

**Review by Jude-Gideon — CHANGES_REQUESTED** [review]
delete

**Pull request closed without merging**
